In [110]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import sigmoid_kernel

In [111]:
data = pd.read_csv(r"datasets/clean_data.csv")

In [112]:
data.shape

(4803, 18)

In [113]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4803 non-null   int64  
 1   genres                4803 non-null   object 
 2   id                    4803 non-null   int64  
 3   keywords              4803 non-null   object 
 4   original_language     4803 non-null   object 
 5   original_title        4803 non-null   object 
 6   overview              4800 non-null   object 
 7   popularity            4803 non-null   float64
 8   production_companies  4803 non-null   object 
 9   release_date          4802 non-null   object 
 10  revenue               4803 non-null   int64  
 11  runtime               4801 non-null   float64
 12  spoken_languages      4803 non-null   object 
 13  tagline               3959 non-null   object 
 14  vote_average          4803 non-null   float64
 15  vote_count           

In [114]:
data.dtypes

budget                    int64
genres                   object
id                        int64
keywords                 object
original_language        object
original_title           object
overview                 object
popularity              float64
production_companies     object
release_date             object
revenue                   int64
runtime                 float64
spoken_languages         object
tagline                  object
vote_average            float64
vote_count                int64
cast                     object
crew                     object
dtype: object

In [115]:
data["overview"]

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...                        
4798    El Mariachi just wants to play his guitar and ...
4799    A newlywed couple's honeymoon is upended by th...
4800    "Signed, Sealed, Delivered" introduces a dedic...
4801    When ambitious New York attorney Sam is sent t...
4802    Ever since the second grade when he first saw ...
Name: overview, Length: 4803, dtype: object

In [116]:
data["overview"][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [117]:
data["overview"].isnull().sum()

np.int64(3)

In [118]:
data["overview"] = data["overview"].fillna("")

In [119]:
data["overview"].isnull().sum()

np.int64(0)

In [120]:
tfv = TfidfVectorizer(
    min_df=3, max_features=None, ngram_range=(1, 3), stop_words="english"
)

In [121]:
tfv_matrix = tfv.fit_transform(data["overview"])

In [122]:
tfv_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 121480 stored elements and shape (4803, 9919)>

In [123]:
tfv_matrix.shape

(4803, 9919)

In [124]:
data["overview"].shape

(4803,)

In [125]:
data["overview"][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [126]:
tfv_matrix.toarray()[0]

array([0., 0., 0., ..., 0., 0., 0.], shape=(9919,))

In [127]:
tfv_matrix[0].T.toarray()

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], shape=(9919, 1))

In [128]:
X = tfv_matrix.toarray()

In [129]:
df2 = pd.DataFrame(X)

In [ ]:
df2

In [ ]:
data["overview"]

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...                        
4798    El Mariachi just wants to play his guitar and ...
4799    A newlywed couple's honeymoon is upended by th...
4800    "Signed, Sealed, Delivered" introduces a dedic...
4801    When ambitious New York attorney Sam is sent t...
4802    Ever since the second grade when he first saw ...
Name: overview, Length: 4803, dtype: object

In [ ]:
sig = sigmoid_kernel(tfv_matrix, tfv_matrix)

In [ ]:
sig

array([[0.76163649, 0.76159416, 0.76159416, ..., 0.76159416, 0.76159416,
        0.76159416],
       [0.76159416, 0.76163649, 0.76159416, ..., 0.76159519, 0.76159416,
        0.76159416],
       [0.76159416, 0.76159416, 0.76163649, ..., 0.76159484, 0.76159416,
        0.76159416],
       ...,
       [0.76159416, 0.76159519, 0.76159484, ..., 0.76163649, 0.76159488,
        0.76159447],
       [0.76159416, 0.76159416, 0.76159416, ..., 0.76159488, 0.76163649,
        0.76159467],
       [0.76159416, 0.76159416, 0.76159416, ..., 0.76159447, 0.76159467,
        0.76163649]], shape=(4803, 4803))

In [ ]:
sig[0]

array([0.76163649, 0.76159416, 0.76159416, ..., 0.76159416, 0.76159416,
       0.76159416], shape=(4803,))

In [ ]:
sig[1]

array([0.76159416, 0.76163649, 0.76159416, ..., 0.76159519, 0.76159416,
       0.76159416], shape=(4803,))

In [ ]:
title = data["original_title"]

In [ ]:
title[4802]

'My Date with Drew'

In [ ]:
index = data.index
index

RangeIndex(start=0, stop=4803, step=1)

In [ ]:
indices = pd.Series(data=data.index, index=data["original_title"]).drop_duplicates()

In [ ]:
indices

original_title
Avatar                                         0
Pirates of the Caribbean: At World's End       1
Spectre                                        2
The Dark Knight Rises                          3
John Carter                                    4
                                            ... 
El Mariachi                                 4798
Newlyweds                                   4799
Signed, Sealed, Delivered                   4800
Shanghai Calling                            4801
My Date with Drew                           4802
Length: 4803, dtype: int64

In [ ]:
indices["Avatar"]

np.int64(0)

In [ ]:
sig[indices["Avatar"]]

array([0.76163649, 0.76159416, 0.76159416, ..., 0.76159416, 0.76159416,
       0.76159416], shape=(4803,))

In [ ]:
list(sig[indices["Avatar"]])

[np.float64(0.76163649309625),
 np.float64(0.7615941559557649),
 np.float64(0.7615941559557649),
 np.float64(0.761595125164868),
 np.float64(0.7615941559557649),
 np.float64(0.761595309447695),
 np.float64(0.7615941559557649),
 np.float64(0.7615959082558289),
 np.float64(0.7615941559557649),
 np.float64(0.7615941559557649),
 np.float64(0.7615941559557649),
 np.float64(0.7615950846887262),
 np.float64(0.7615941559557649),
 np.float64(0.7615941559557649),
 np.float64(0.7615941559557649),
 np.float64(0.7615941559557649),
 np.float64(0.7615941559557649),
 np.float64(0.7615941559557649),
 np.float64(0.7615941559557649),
 np.float64(0.7615941559557649),
 np.float64(0.7615941559557649),
 np.float64(0.7615941559557649),
 np.float64(0.7615941559557649),
 np.float64(0.7615941559557649),
 np.float64(0.7615941559557649),
 np.float64(0.7615941559557649),
 np.float64(0.7615957270499999),
 np.float64(0.7615962614863476),
 np.float64(0.7615941559557649),
 np.float64(0.7615952950243241),
 np.float64(0.

In [ ]:
len(list(sig[indices["Avatar"]]))

4803

In [ ]:
list(enumerate(list(sig[indices["Avatar"]])))

[(0, np.float64(0.76163649309625)),
 (1, np.float64(0.7615941559557649)),
 (2, np.float64(0.7615941559557649)),
 (3, np.float64(0.761595125164868)),
 (4, np.float64(0.7615941559557649)),
 (5, np.float64(0.761595309447695)),
 (6, np.float64(0.7615941559557649)),
 (7, np.float64(0.7615959082558289)),
 (8, np.float64(0.7615941559557649)),
 (9, np.float64(0.7615941559557649)),
 (10, np.float64(0.7615941559557649)),
 (11, np.float64(0.7615950846887262)),
 (12, np.float64(0.7615941559557649)),
 (13, np.float64(0.7615941559557649)),
 (14, np.float64(0.7615941559557649)),
 (15, np.float64(0.7615941559557649)),
 (16, np.float64(0.7615941559557649)),
 (17, np.float64(0.7615941559557649)),
 (18, np.float64(0.7615941559557649)),
 (19, np.float64(0.7615941559557649)),
 (20, np.float64(0.7615941559557649)),
 (21, np.float64(0.7615941559557649)),
 (22, np.float64(0.7615941559557649)),
 (23, np.float64(0.7615941559557649)),
 (24, np.float64(0.7615941559557649)),
 (25, np.float64(0.7615941559557649)),


In [ ]:
sigma_scores = sorted(
    list(enumerate(list(sig[indices["Avatar"]]))), key=lambda x: x[1], reverse=True
)

In [ ]:
sigma_scores

[(0, np.float64(0.76163649309625)),
 (1341, np.float64(0.7616030155858681)),
 (634, np.float64(0.7616028561141562)),
 (3604, np.float64(0.761601930611584)),
 (2130, np.float64(0.7616015339622925)),
 (775, np.float64(0.7616011086528326)),
 (529, np.float64(0.7615996114069044)),
 (151, np.float64(0.7615991171152051)),
 (311, np.float64(0.7615990624497703)),
 (847, np.float64(0.7615987706430224)),
 (570, np.float64(0.7615986450599548)),
 (942, np.float64(0.7615984376900236)),
 (36, np.float64(0.761597988130195)),
 (1610, np.float64(0.7615979793934843)),
 (3070, np.float64(0.7615978406764746)),
 (1033, np.float64(0.7615978182403835)),
 (2628, np.float64(0.7615977834088159)),
 (1784, np.float64(0.7615977150705628)),
 (2578, np.float64(0.7615976778191441)),
 (150, np.float64(0.7615976453752452)),
 (3724, np.float64(0.7615975951237102)),
 (1013, np.float64(0.761597590729192)),
 (4211, np.float64(0.7615975631290405)),
 (1213, np.float64(0.7615975380289366)),
 (1345, np.float64(0.76159745490752

In [ ]:
sigma_scores[1:11]

[(1341, np.float64(0.7616030155858681)),
 (634, np.float64(0.7616028561141562)),
 (3604, np.float64(0.761601930611584)),
 (2130, np.float64(0.7616015339622925)),
 (775, np.float64(0.7616011086528326)),
 (529, np.float64(0.7615996114069044)),
 (151, np.float64(0.7615991171152051)),
 (311, np.float64(0.7615990624497703)),
 (847, np.float64(0.7615987706430224)),
 (570, np.float64(0.7615986450599548))]

In [ ]:
ind = [index[0] for index in sigma_scores[1:11]]

In [ ]:
ind

[1341, 634, 3604, 2130, 775, 529, 151, 311, 847, 570]

In [ ]:
data["original_title"].iloc[ind]

1341                Obitaemyy Ostrov
634                       The Matrix
3604                       Apollo 18
2130                    The American
775                        Supernova
529                 Tears of the Sun
151                          Beowulf
311     The Adventures of Pluto Nash
847                         Semi-Pro
570                           Ransom
Name: original_title, dtype: object

In [ ]:
data["original_title"].iloc[ind]

1341                Obitaemyy Ostrov
634                       The Matrix
3604                       Apollo 18
2130                    The American
775                        Supernova
529                 Tears of the Sun
151                          Beowulf
311     The Adventures of Pluto Nash
847                         Semi-Pro
570                           Ransom
Name: original_title, dtype: object

In [ ]:
def give_rec(title, model, topk=10):
    if title not in indices:
        raise ValueError(f"Cannot find '{title}' in dataset.")

    idx = indices[title]
    scores = list(enumerate(model[idx]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)
    scores = scores[1 : topk + 1]
    movie_indices = [i for i, _ in scores]
    return data.iloc[movie_indices][["original_title", "overview"]]

In [ ]:
give_rec("Avatar", sig)

,original_title,overview
1341,Obitaemyy Ostrov,"On the threshold of 22nd century, furrowing th..."
634,The Matrix,"Set in the 22nd century, The Matrix tells the ..."
3604,Apollo 18,"Officially, Apollo 17 was the last manned miss..."
2130,The American,Dispatched to a small Italian town to await fu...
775,Supernova,"Set in the 22nd century, when a battered salva..."
529,Tears of the Sun,Navy SEAL Lieutenant A.K. Waters and his elite...
151,Beowulf,"6th-century Scandinavian warrior, Beowulf emba..."
311,The Adventures of Pluto Nash,"The year is 2087, the setting is the moon. Plu..."
847,Semi-Pro,"Jackie Moon is the owner, promoter, coach, and..."
570,Ransom,"When a rich man's son is kidnapped, he coopera..."
